### ISSUE TITLE
Merge evaluation affordances

### ISSUE THREAD

**Issue by gcotelli** [ba-st/Willow#132]
@mtabacman what's your opinion on combining 
- `determineBehaviorByEvaluating:`  with `evaluate:` 
- `determineBehaviorByEvaluating:with:` with `evaluate:with:`

So if you provide a parameter in the block for evaluate we inject the response and behave like determineBehaviorByEvaluating is doing now.

So you can do:
```smalltalk
evaluate: [ ... ]
evaluate: [:response | ... ]
evaluate: [:parameter | ... ] with: xxx
evaluate: [:parameter :response | ... ] with: xxx
```

**Comment by mtabacman** [comment]
Fixed by #174
