### ISSUE TITLE
Improve detection of duplicated serialization commands

### ISSUE THREAD

**Issue by gcotelli** [ba-st/Willow#148]
Some components already include a serialization command upon creation, so sending to its interpreter a `serializeIt` action ends up in a duplicated field sent in the AJAX Post. This is problematic to some web servers.

If we can detect this duplication we can warn the user about it before running into the problem.

**Comment by fxgallego** [comment]
@gcotelli We are going to change the way our server process params. Anyway this would be useful to avoid hard to debug issues.
