### ISSUE TITLE
Willow in Pharo and VW

### ISSUE THREAD

**Issue by Shaping** [ba-st/Willow#153]
Hi Gabriel. 

I'm not sure my direct e-mails, sent in response to your first reply, are being received.

I've been trying to port from VW to Pharo for almost 14 years.  Pharo still has serious basic GUI problems, like not being able to accommodate a small change in font size without truncating labels in, for example, Setting and the Iceberg client.  I recently posted an example of this, with a screenshot, to pharo-users and pharo-dev.  Users and devs seem not to be able to see that correct framing of text renderings is broken in Pharo, in spite of all the slick GUI improvements, like GT.  Or, they just don't want to bother with the fix until Spec2 is ready.  This basic flaw and the general slowness of the GUI have kept me away.  Spec2/GTK3 is here, I think--and that will provide the needed snap in the GUI--but the key issue is whether anyone is actually now using Spec2 to retool, say, the System Browser.  I don't know.  Do you?

As I read through the Willow materials, I'm increasingly impressed with the grace and utility of this framework.  Thank you for your work and good use of common sense.

I have a time-series (candlestick chart) app I'm implementing from scratch in VW using, not Wrapper (a big pain), but the Panel hierarchy (prototypical, never officially released by Cincom). I'm also trying to revive Cincom's Widgetry (better than Wrapper, but still another failed incomplete, buggy framework).  All of this work seems like a waste of energy when I see how beautiful web GUIs are in the jQuery UI.   

The latest Cincom Seaside is from 2017-06; the latest Willow is from 2003-03.  The Willow version is clearly old. I'm not sure about Seaside.  I think it has been updated since then, but I don't know why it would not be also in the Cincom repo.  Do know when these will updated in the Cincom repo?.  I would like convert my local-client app to a web app, and build it with Seaside and Willow.

To use Pharo, I would need to prot, and I have little time and a lot of code.  Pharo's Git interface still concerns me.  I've never been able to make it work reliably in Pharo, even when I can read the text labels.  

I would like to practice with Willow anyway.  Can you tell me how to proceed with Willow in Pharo 8 64-bit (stable)?  The prebuilt Willow playground image appearing in Pharo Launcher 2.0 is broken.  I get walkbacks just selecting items in the tree after launching the demo.

Thanks.

Shaping

**Comment by gcotelli** [comment]
Answered in ba-st/Willow-Playground#42
