### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by tblanchard** [ba-st/Willow#162]
Support for bootstrap 4?  What would it take?

**Comment by fortizpenaloza** [comment]
Hi @tblanchard , see https://github.com/ba-st/Willow-Bootstrap

**Comment by tblanchard** [comment]
That's great!

I will give it a try.

You should update this part of the Willow Readme.md to reduce confusion.

**Comment by gcotelli** [comment]
I've updated the readme. I'm pushing some updates on Willow Boostrap now, but if you take the latest release you should be Ok.
