### ISSUE TITLE
Fix broken reference in README

### ISSUE THREAD

**Issue by tinchodias** [ba-st/Willow#168]
README refers to "#willow channel at ba-st.slack.com" but I couldn't see it:

![Screenshot from 2020-06-02 18-19-12](https://user-images.githubusercontent.com/3044265/83575572-d1b1e800-a4fd-11ea-9658-ffa3ab660e76.png)

**Comment by gcotelli** [comment]
There's a #willow channel. Click on the plus sign and add it. Not all the
channels are added by default on Slack

**Comment by tinchodias** [comment]
Didn't know it works like that. In Discord/pharo you see the channels when you enter, I think. 

So... do we consider this issue as invalid?
