### ISSUE TITLE
LoadingNotificationCommand may never execute the "then" argument

### ISSUE THREAD

**Issue by jvanecek** [ba-st/Willow#207]
LoadingNotificationCommand it was designed to do an action before an ajax (tipically "display message") and do another when completed (hide said message).

Since the block passed in the #then: key argument is considered a modelLoadingInstruction, it may never be executed if no ajax is configured to the component, leaving the action executed by the serverIndependentAction (defined in the #executing: key argument) not undone. 

This could be solved if this command works as TemporarilyDisablingCommand, where both actions are actually one priorityAction.

**Comment by gcotelli** [comment]
Fixed by #208
