### ISSUE TITLE
Conditional AJAX call

### ISSUE THREAD

**Issue by mtabacman** [ba-st/Willow#54]
The current protocol lacks a command to do a Javascript evaluation to decide whether to call the server.
Ideally it would be a mix of 
evaluate:with: 
confirmAsking:
executeOnClient:

**Comment by gcotelli** [comment]
@mtabacman I think it's covered by `onlyWhen: aStringCondition determineBehaviorByEvaluating: aCallbackBlock with: aParameter`.

The condition part needs some improvement, but what do you think? Can we close this issue?
